imageupload/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='list'),
    path('new/', views.PostCreate.as_view(), name='create'),
    path('<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('<int:pk>/edit/', views.PostUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def post_image_path(instance, filename):
    return 'posts/{}/{}'.format(instance.pk, filename)

# Create your models here.
class Post(models.Model):
    # image = models.ImageField()
    image = ProcessedImageField(
                upload_to = post_image_path,
                processors = [ResizeToFill(300, 300)],
                format = 'JPEG',
                options = {'quality': 90}
            )
    content = models.TextField()
    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post


# Create your views here.
class PostList(ListView):
    model = Post
    
    
class PostCreate(CreateView):
    model = Post
    fields = ['image', 'content',]
    
    
class PostDetail(DetailView):
    model = Post
    

class PostUpdate(UpdateView):
    model = Post
    fields = ['image', 'content',]


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')

posts/templates/posts/post_confirm_delete.html
<h1>Post Delete</h1>

<form method='post'>
    {%csrf_token%}
    <p>{{post.pk}}번, 정말 삭제 하시겠습니까?</p>
    <input type="submit" value="ok"/>
</form>

posts/templates/posts/post_detail.html
<h1>Post Detail</h1>

<a href="{%url 'posts:update' pk=post.pk%}">Edit</a>
<a href="{%url 'posts:delete' pk=post.pk%}">Delete</a>

<div>
    <img src="{{post.image.url}}"></img>
    <p>{{post.content}}</p>
</div>

posts/templates/posts/post_form.html
<h1>Post Create</h1>

<form method='post' enctype='multipart/form-data'>
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value='Submit'/>
</form>

posts/templates/posts/post_list.html
<h1>PostList</h1>

<a href="{%url 'posts:create'%}">New Post</a>

<ul>
    {%for post in post_list%}
    <li>
        <a href="{%url 'posts:detail' pk=post.pk%}">
            <img src="{{post.image.url}}"></img>
        </a>
        <p>{{post.content}}</p>
    </li>
    {%endfor%}
</ul>